name: insightwave
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - flask-cors=3.0.10
  - werkzeug=2.3.7
  - pandas=1.5.3
  - numpy=1.23.5
  - matplotlib=3.5.3
  - seaborn=0.12.2
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - squarify=0.4.3
  - pip
  - pip:
    - python-dotenv
    - Flask-Caching
    - Flask-JWT-Extended
