name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  NODE_VERSION: '20'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check electron-log installation
      run: |
        cd frontend
        npm list electron-log || npm install electron-log
      shell: bash
      
    - name: Build Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          cd frontend
          npm run dist:windows
      shell: bash

    - name: Install dependencies
      run: |
        npm install -g npm@latest
        cd frontend
        npm ci
      shell: bash

    - name: Check icon file
      run: |
        if (Test-Path frontend/build/icon.ico) {
          echo "Icon file exists"
        } else {
          echo "Icon file is missing"
          exit 1
        }
      shell: pwsh

    - name: Build Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd frontend
        npm run dist:windows
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows
        path: frontend/dist

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-windows
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./artifacts/*.exe
          ./artifacts/*.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}