name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.9'

jobs:
  build-linux-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    # ... (保留之前的步骤，但移除 macOS 特定的步骤)

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        npm install -g npm@latest
        cd frontend
        npm ci
      
    - name: Build and Publish Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd frontend
        npm run dist:macos-latest
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-macos-latest
        path: frontend/dist

  release:
    needs: [build-linux-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    # ... (保留之前的发布步骤)